
import turtle

turtle.Screen().bgcolor("orange")
#LETRA D
turtle.shape('turtle')
turtle.up()
turtle.goto(-800,0)
turtle.down()
turtle.shape('turtle')
turtle.pencolor('red')
turtle.pensize(10)
turtle.forward(200)
turtle.left(50)
turtle.shape('turtle')
turtle.pencolor('blue')
turtle.forward(200)
turtle.left(40)
turtle.shape('turtle')
turtle.pencolor('pink')
turtle.forward(200)
turtle.left(50)
turtle.shape('turtle')
turtle.pencolor('purple')
turtle.forward(200)
turtle.left(40)
turtle.shape('turtle')
turtle.pencolor('silver')
turtle.forward(180)
turtle.left(90)
turtle.shape('turtle')
turtle.pencolor('green')
turtle.forward(480)
turtle.left(90)

#ESPACIO
turtle.up()
turtle.goto(-300,0)
turtle.down()

#LETRA I
turtle.left(90)
turtle.forward(300)
turtle.up()
turtle.goto(-300,400)
turtle.down()
turtle.dot(15,'red')
turtle.up()
turtle.goto(-300,0)
turtle.down()

#ESPACIO
turtle.up()
turtle.goto(0,0)
turtle.down()

#LETRA E
turtle.shape('turtle')
turtle.pencolor('red')
turtle.left(-60)
turtle.forward(250)
turtle.left(180)
turtle.shape('turtle')
turtle.pencolor('blue')
turtle.up()
turtle.forward(250)
turtle.down()
turtle.left(-90)
turtle.forward(250)
turtle.left(290)
turtle.shape('turtle')
turtle.pencolor('silver')
turtle.forward(220)
turtle.left(270)
turtle.shape('turtle')
turtle.pencolor('purple')
turtle.forward(220)
turtle.left(-135)
turtle.shape('turtle')
turtle.pencolor('pink')
turtle.forward(310)
turtle.left(115)
turtle.shape('turtle')
turtle.pencolor('blue')
turtle.up()
turtle.forward(250)
turtle.down()

#ESPACIO
turtle.up()
turtle.goto(350,0)
turtle.down()

#LETRA G
turtle.shape('turtle')
turtle.pencolor('yellow')
turtle.forward(200)
turtle.left(60)
turtle.shape('turtle')
turtle.pencolor('Violet')
turtle.forward(200)
turtle.left(90)
turtle.shape('turtle')
turtle.pencolor('Brown')
turtle.forward(500)
turtle.left(50)
turtle.shape('turtle')
turtle.pencolor('Grey')
turtle.forward(210)
turtle.left(90)
turtle.shape('turtle')
turtle.pencolor('Navy')
turtle.forward(210)
turtle.left(90)
turtle.shape('turtle')
turtle.pencolor('red')
turtle.forward(210)
turtle.left(90)
turtle.shape('turtle')
turtle.pencolor('black')
turtle.forward(210)
turtle.left(-140)
turtle.up()
turtle.forward(250)
turtle.left(90)
turtle.down()

#ESPACIO
turtle.up()
turtle.goto(875,100)
turtle.down()

#LETRA O
turtle.shape('turtle')
turtle.pencolor('silver')
turtle.left(45)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('pink')
turtle.left(90)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('purple')
turtle.left(90)
turtle.forward(200)
turtle.shape('turtle')
turtle.pencolor('green')
turtle.left(90)
turtle.forward(200)
turtle.left(45)

#ESPACIO
turtle.up()
turtle.goto(-600,-275)
turtle.down()

#LETRA C
turtle.shape('turtle')
turtle.pencolor('green')
turtle.backward(200)
turtle.left(225)
turtle.shape('turtle')
turtle.pencolor('pink')
turtle.forward(200)
turtle.left(45)
turtle.shape('turtle')
turtle.pencolor('red')
turtle.forward(200)
turtle.left(45)
turtle.shape('turtle')
turtle.pencolor('magenta')
turtle.forward(200)
turtle.left(45)
turtle.shape('turtle')
turtle.pencolor('cyan')
turtle.forward(200)

#ESPACIO
turtle.up()
turtle.goto(-500,-750)
turtle.down()

#LETRA A

turtle.shape('turtle')
turtle.pencolor('blue')
turtle.circle(100)
turtle.up()
turtle.circle(100,90)
turtle.down()
turtle.shape('turtle')
turtle.pencolor('pink')
turtle.up()
turtle.goto(-400,-750)
turtle.down()
turtle.forward(250)
turtle.left(90)
turtle.forward(200)
turtle.left(180)
turtle.up()
turtle.goto(-400,-750)
turtle.down()

#ESPACIO
turtle.up()
turtle.goto(-300,-750)
turtle.down()

#LETRA L

turtle.shape('turtle')
turtle.pencolor('Brown')
turtle.left(90)
turtle.forward(500)
turtle.up()
turtle.goto(-300,-750)
turtle.down()

#ESPACIO
turtle.up()
turtle.goto(-50,-600)
turtle.down()

#LETRA D
turtle.shape('turtle')
turtle.pencolor('red')
turtle.circle(100)

